# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 3ad024c27dfc632f5fc282f5a186127596d8d393cf557064bdc45913371c98a826cc952ef46a06aa79a27a6c191c96bb197a95c73fbe368b04ceb8c7b44306bd

test:
  secret_key_base: 60e6294185b3a4f6b3d581e808b52b12ba4885fcff339b1a93cf0e0fb94a46ed37f37bb8114944e8233f088ab7a11492be628bbbec2475079345993288b695a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
